variables:
  DOCKER_DRIVER: overlay2

stages:
  - docker

dockerize:
  stage: docker
  image: code.chs.usgs.gov:5001/wma/hydrogeoenv:19.03.13-dind
  variables:
    LINUX_TAG: wma/hydrogeoenv/linux:$CI_COMMIT_REF_SLUG
  script:
    - docker build -t $LINUX_TAG --build-arg BASE_CONTAINER=code.chs.usgs.gov:5001/wma/hydrogeoenv:bionic-20200630 linux/
    - docker push $LINUX_TAG
  tags:
    - chs-shared
