build-docker:
  stage: build
  image: code.chs.usgs.gov:5001/usgs-chs/chs-library/docker/images/docker:19.03-dind
  variables:
    LINUX_TAG: wma/hydrogeoenv/linux:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $LINUX_TAG --build-arg BASE_CONTAINER=ubuntu:bionic-20200630 linux/
    - docker push $IMAGE_TAG
  tags:
    - chs-shared
