variables:
  DOCKER_DRIVER: overlay2

stages:
  - docker

dockerize:
  stage: docker
  image: code.chs.usgs.gov:5001/wma/hydrogeoenv:stable-dind
  variables:
    LINUX_TAG: wma/hydrogeoenv/linux:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin code.chs.usgs.gov:5001
  script:
    - docker build -t $LINUX_TAG --build-arg BASE_CONTAINER=code.chs.usgs.gov:5001/wma/hydrogeoenv:bionic-20200630 linux/
    - docker push $IMAGE_TAG
  tags:
    - chs-shared
