variables:
  DOCKER_DRIVER: overlay2

stages:
  - docker

services:
  - name: code.chs.usgs.gov:5001/wma/hydrogeoenv:19.03.13-dind
    alias: docker

dockerize:
  stage: docker
  image:
    code.chs.usgs.gov:5001/wma/hydrogeoenv:19.03.13-dind
  variables:
    LINUX_TAG: code.chs.usgs.gov:5001/wma/hydrogeoenv:linux-$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin code.chs.usgs.gov:5001
  script:
    - docker build -t $LINUX_TAG --build-arg BASE_CONTAINER=code.chs.usgs.gov:5001/wma/hydrogeoenv:bionic-20200630 linux/
    - docker push $LINUX_TAG
  tags:
    - chs-shared
